"""Map stored icon keys to Flet IconData (large shared collection)."""

from __future__ import annotations

import flet as ft


def _icons() -> dict[str, ft.IconData]:
    """Build key → Icon mapping (missing attrs skipped gracefully)."""
    names = {
        "category": "CATEGORY",
        "category_outlined": "CATEGORY_OUTLINED",
        "restaurant": "RESTAURANT",
        "fastfood": "FASTFOOD",
        "local_cafe": "LOCAL_CAFE",
        "local_bar": "LOCAL_BAR",
        "cake": "CAKE",
        "lunch_dining": "LUNCH_DINING",
        "dinner_dining": "DINNER_DINING",
        "takeout_dining": "TAKEOUT_DINING",
        "kebab_dining": "KEBAB_DINING",
        "brunch_dining": "BRUNCH_DINING",
        "kitchen": "KITCHEN",
        "egg": "EGG",
        "restaurant_menu": "RESTAURANT_MENU",
        "shopping_cart": "SHOPPING_CART",
        "shopping_bag": "SHOPPING_BAG",
        "shopping_basket": "SHOPPING_BASKET",
        "store": "STORE",
        "storefront": "STOREFRONT",
        "local_grocery_store": "LOCAL_GROCERY_STORE",
        "local_mall": "LOCAL_MALL",
        "local_offer": "LOCAL_OFFER",
        "directions_car": "DIRECTIONS_CAR",
        "directions_bus": "DIRECTIONS_BUS",
        "train": "TRAIN",
        "flight": "FLIGHT",
        "flight_takeoff": "FLIGHT_TAKEOFF",
        "local_taxi": "LOCAL_TAXI",
        "two_wheeler": "TWO_WHEELER",
        "electric_scooter": "ELECTRIC_SCOOTER",
        "local_gas_station": "LOCAL_GAS_STATION",
        "directions_walk": "DIRECTIONS_WALK",
        "directions_boat": "DIRECTIONS_BOAT",
        "home": "HOME",
        "apartment": "APARTMENT",
        "hotel": "HOTEL",
        "cottage": "COTTAGE",
        "weekend": "WEEKEND",
        "chair": "CHAIR",
        "bed": "BED",
        "electrical_services": "ELECTRICAL_SERVICES",
        "lightbulb": "LIGHTBULB",
        "water_drop": "WATER_DROP",
        "wifi": "WIFI",
        "phone_android": "PHONE_ANDROID",
        "plumbing": "PLUMBING",
        "local_hospital": "LOCAL_HOSPITAL",
        "medical_services": "MEDICAL_SERVICES",
        "healing": "HEALING",
        "medication": "MEDICATION",
        "monitor_heart": "MONITOR_HEART",
        "fitness_center": "FITNESS_CENTER",
        "spa": "SPA",
        "psychology": "PSYCHOLOGY",
        "emergency": "EMERGENCY",
        "bloodtype": "BLOODTYPE",
        "movie": "MOVIE",
        "sports_esports": "SPORTS_ESPORTS",
        "music_note": "MUSIC_NOTE",
        "theater_comedy": "THEATER_COMEDY",
        "sports_soccer": "SPORTS_SOCCER",
        "sports_basketball": "SPORTS_BASKETBALL",
        "sports_tennis": "SPORTS_TENNIS",
        "casino": "CASINO",
        "nightlife": "NIGHTLIFE",
        "videogame_asset": "VIDEOGAME_ASSET",
        "checkroom": "CHECKROOM",
        "diamond": "DIAMOND",
        "watch": "WATCH",
        "school": "SCHOOL",
        "menu_book": "MENU_BOOK",
        "work": "WORK",
        "business_center": "BUSINESS_CENTER",
        "mail": "MAIL",
        "print": "PRINT",
        "badge": "BADGE",
        "payments": "PAYMENTS",
        "attach_money": "ATTACH_MONEY",
        "savings": "SAVINGS",
        "account_balance": "ACCOUNT_BALANCE",
        "account_balance_wallet": "ACCOUNT_BALANCE_WALLET",
        "credit_card": "CREDIT_CARD",
        "monetization_on": "MONETIZATION_ON",
        "token": "TOKEN",
        "generating_tokens": "GENERATING_TOKENS",
        "loyalty": "LOYALTY",
        "style": "STYLE",
        "euro_symbol": "EURO_SYMBOL",
        "currency_pound": "CURRENCY_POUND",
        "currency_ruble": "CURRENCY_RUBLE",
        "currency_yen": "CURRENCY_YEN",
        "currency_yuan": "CURRENCY_YUAN",
        "currency_rupee": "CURRENCY_RUPEE",
        "currency_lira": "CURRENCY_LIRA",
        "currency_franc": "CURRENCY_FRANC",
        "currency_bitcoin": "CURRENCY_BITCOIN",
        "currency_exchange": "CURRENCY_EXCHANGE",
        "paid": "PAID",
        "sell": "SELL",
        "atm": "ATM",
        "contactless": "CONTACTLESS",
        "qr_code_2": "QR_CODE_2",
        "safe": "LOCK",
        "point_of_sale": "POINT_OF_SALE",
        "storefront": "STOREFRONT",
        "trending_up": "TRENDING_UP",
        "show_chart": "SHOW_CHART",
        "card_giftcard": "CARD_GIFTCARD",
        "redeem": "REDEEM",
        "celebration": "CELEBRATION",
        "pets": "PETS",
        "child_care": "CHILD_CARE",
        "baby_changing_station": "BABY_CHANGING_STATION",
        "family_restroom": "FAMILY_RESTROOM",
        "diversity_3": "DIVERSITY_3",
        "cleaning_services": "CLEANING_SERVICES",
        "handyman": "HANDYMAN",
        "build": "BUILD",
        "local_laundry_service": "LOCAL_LAUNDRY_SERVICE",
        "content_cut": "CONTENT_CUT",
        "brush": "BRUSH",
        "palette": "PALETTE",
        "camera_alt": "CAMERA_ALT",
        "photo_camera": "PHOTO_CAMERA",
        "computer": "COMPUTER",
        "laptop": "LAPTOP",
        "headphones": "HEADPHONES",
        "smartphone": "SMARTPHONE",
        "cloud": "CLOUD",
        "public": "PUBLIC",
        "map": "MAP",
        "park": "PARK",
        "beach_access": "BEACH_ACCESS",
        "local_florist": "LOCAL_FLORIST",
        "eco": "ECO",
        "bolt": "BOLT",
        "local_fire_department": "LOCAL_FIRE_DEPARTMENT",
        "smoking_rooms": "SMOKING_ROOMS",
        "liquor": "LIQUOR",
        "coffee": "COFFEE",
        "bakery_dining": "BAKERY_DINING",
        "ramen_dining": "RAMEN_DINING",
        "icecream": "ICECREAM",
        "local_pizza": "LOCAL_PIZZA",
        "set_meal": "SET_MEAL",
        "receipt_long": "RECEIPT_LONG",
        "request_quote": "REQUEST_QUOTE",
        "price_check": "PRICE_CHECK",
        "volunteer_activism": "VOLUNTEER_ACTIVISM",
        "favorite": "FAVORITE",
        "star": "STAR",
        "emoji_events": "EMOJI_EVENTS",
        "military_tech": "MILITARY_TECH",
        "handshake": "HANDSHAKE",
        "groups": "GROUPS",
        "person": "PERSON",
        "face": "FACE",
        "self_improvement": "SELF_IMPROVEMENT",
        "nightlight": "NIGHTLIGHT",
        "wb_sunny": "WB_SUNNY",
        "umbrella": "UMBRELLA",
        "directions_bike": "DIRECTIONS_BIKE",
        "pedal_bike": "PEDAL_BIKE",
        "sailing": "SAILING",
        "subway": "SUBWAY",
        "tram": "TRAM",
        "local_shipping": "LOCAL_SHIPPING",
        "inventory_2": "INVENTORY_2",
        "wallet": "ACCOUNT_BALANCE_WALLET",
        "luggage": "LUGGAGE",
        "forest": "FOREST",
        "hiking": "HIKING",
        "museum": "MUSEUM",
        "cabin": "CABIN",
        "terrain": "TERRAIN",
        "more_horiz": "MORE_HORIZ",
        "apps": "APPS",
    }
    mapping: dict[str, ft.IconData] = {}
    for key, attr in names.items():
        icon = getattr(ft.Icons, attr, None)
        if icon is not None:
            mapping[key] = icon
    # Fallback always present.
    mapping.setdefault("category", ft.Icons.CATEGORY)
    return mapping


ICON_MAP: dict[str, ft.IconData] = _icons()


def resolve_icon(name: str | None, *, default: str = "category") -> ft.IconData:
    """Resolve a stored icon key to Flet IconData."""
    if name and name in ICON_MAP:
        return ICON_MAP[name]
    return ICON_MAP.get(default, ft.Icons.CATEGORY)
